name: elisa
favicon: null
layout_spectrum: 0.5875764947850257
typography_spectrum: 0.02174880960956216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.20191202778369188
  lightness: 0.3404637861531228
  saturation: 0.44299492915160954
  rhythmicContrast: 0.2604189545381814
purpose: []
